databases:
  - name: giveaway-db

services:
  - type: web
    name: giveaway-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: TZ
        value: America/New_York
      - key: DATABASE_URL
        fromDatabase:
          name: giveaway-db
          property: connectionString
